name: bazar_backend
description: Backend server for Bazar using Neon PostgreSQL
version: 0.1.0
publish_to: 'none'
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  dotenv: ^4.1.0
  logging: ^1.2.0
  meta: ^1.12.0
  postgres: ^2.7.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.8
